// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fabric.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Transaction_Type int32

const (
	Transaction_UNDEFINED Transaction_Type = 0
	// deploy a chaincode to the network and call `Init` function
	Transaction_CHAINCODE_DEPLOY Transaction_Type = 1
	// call a chaincode `Invoke` function as a transaction
	Transaction_CHAINCODE_INVOKE Transaction_Type = 2
	// call a chaincode `query` function
	Transaction_CHAINCODE_QUERY Transaction_Type = 3
	// terminate a chaincode; not implemented yet
	Transaction_CHAINCODE_TERMINATE Transaction_Type = 4
)

var Transaction_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "CHAINCODE_DEPLOY",
	2: "CHAINCODE_INVOKE",
	3: "CHAINCODE_QUERY",
	4: "CHAINCODE_TERMINATE",
}
var Transaction_Type_value = map[string]int32{
	"UNDEFINED":           0,
	"CHAINCODE_DEPLOY":    1,
	"CHAINCODE_INVOKE":    2,
	"CHAINCODE_QUERY":     3,
	"CHAINCODE_TERMINATE": 4,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}
func (Transaction_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0, 0} }

type PeerEndpoint_Type int32

const (
	PeerEndpoint_UNDEFINED     PeerEndpoint_Type = 0
	PeerEndpoint_VALIDATOR     PeerEndpoint_Type = 1
	PeerEndpoint_NON_VALIDATOR PeerEndpoint_Type = 2
)

var PeerEndpoint_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "VALIDATOR",
	2: "NON_VALIDATOR",
}
var PeerEndpoint_Type_value = map[string]int32{
	"UNDEFINED":     0,
	"VALIDATOR":     1,
	"NON_VALIDATOR": 2,
}

func (x PeerEndpoint_Type) String() string {
	return proto.EnumName(PeerEndpoint_Type_name, int32(x))
}
func (PeerEndpoint_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{8, 0} }

type Message_Type int32

const (
	Message_UNDEFINED               Message_Type = 0
	Message_DISC_HELLO              Message_Type = 1
	Message_DISC_DISCONNECT         Message_Type = 2
	Message_DISC_GET_PEERS          Message_Type = 3
	Message_DISC_PEERS              Message_Type = 4
	Message_DISC_NEWMSG             Message_Type = 5
	Message_CHAIN_TRANSACTION       Message_Type = 6
	Message_SYNC_GET_BLOCKS         Message_Type = 11
	Message_SYNC_BLOCKS             Message_Type = 12
	Message_SYNC_BLOCK_ADDED        Message_Type = 13
	Message_SYNC_STATE_GET_SNAPSHOT Message_Type = 14
	Message_SYNC_STATE_SNAPSHOT     Message_Type = 15
	Message_SYNC_STATE_GET_DELTAS   Message_Type = 16
	Message_SYNC_STATE_DELTAS       Message_Type = 17
	Message_RESPONSE                Message_Type = 20
	Message_CONSENSUS               Message_Type = 21
)

var Message_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "DISC_HELLO",
	2:  "DISC_DISCONNECT",
	3:  "DISC_GET_PEERS",
	4:  "DISC_PEERS",
	5:  "DISC_NEWMSG",
	6:  "CHAIN_TRANSACTION",
	11: "SYNC_GET_BLOCKS",
	12: "SYNC_BLOCKS",
	13: "SYNC_BLOCK_ADDED",
	14: "SYNC_STATE_GET_SNAPSHOT",
	15: "SYNC_STATE_SNAPSHOT",
	16: "SYNC_STATE_GET_DELTAS",
	17: "SYNC_STATE_DELTAS",
	20: "RESPONSE",
	21: "CONSENSUS",
}
var Message_Type_value = map[string]int32{
	"UNDEFINED":               0,
	"DISC_HELLO":              1,
	"DISC_DISCONNECT":         2,
	"DISC_GET_PEERS":          3,
	"DISC_PEERS":              4,
	"DISC_NEWMSG":             5,
	"CHAIN_TRANSACTION":       6,
	"SYNC_GET_BLOCKS":         11,
	"SYNC_BLOCKS":             12,
	"SYNC_BLOCK_ADDED":        13,
	"SYNC_STATE_GET_SNAPSHOT": 14,
	"SYNC_STATE_SNAPSHOT":     15,
	"SYNC_STATE_GET_DELTAS":   16,
	"SYNC_STATE_DELTAS":       17,
	"RESPONSE":                20,
	"CONSENSUS":               21,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{15, 0} }

type Response_StatusCode int32

const (
	Response_UNDEFINED Response_StatusCode = 0
	Response_SUCCESS   Response_StatusCode = 200
	Response_FAILURE   Response_StatusCode = 500
)

var Response_StatusCode_name = map[int32]string{
	0:   "UNDEFINED",
	200: "SUCCESS",
	500: "FAILURE",
}
var Response_StatusCode_value = map[string]int32{
	"UNDEFINED": 0,
	"SUCCESS":   200,
	"FAILURE":   500,
}

func (x Response_StatusCode) String() string {
	return proto.EnumName(Response_StatusCode_name, int32(x))
}
func (Response_StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{16, 0} }

type SyncMsg_Type int32

const (
	SyncMsg_UNDEFINED                 SyncMsg_Type = 0
	SyncMsg_SYNC_STATE_NOTIFY         SyncMsg_Type = 1
	SyncMsg_SYNC_STATE_OPT            SyncMsg_Type = 2
	SyncMsg_SYNC_SESSION_START        SyncMsg_Type = 5
	SyncMsg_SYNC_SESSION_QUERY        SyncMsg_Type = 6
	SyncMsg_SYNC_SESSION_RESPONSE     SyncMsg_Type = 7
	SyncMsg_SYNC_SESSION_END          SyncMsg_Type = 8
	SyncMsg_SYNC_SESSION_GET_BLOCKS   SyncMsg_Type = 11
	SyncMsg_SYNC_SESSION_BLOCKS       SyncMsg_Type = 12
	SyncMsg_SYNC_SESSION_GET_SNAPSHOT SyncMsg_Type = 14
	SyncMsg_SYNC_SESSION_SNAPSHOT     SyncMsg_Type = 15
	SyncMsg_SYNC_SESSION_GET_DELTAS   SyncMsg_Type = 16
	SyncMsg_SYNC_SESSION_DELTAS       SyncMsg_Type = 17
)

var SyncMsg_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "SYNC_STATE_NOTIFY",
	2:  "SYNC_STATE_OPT",
	5:  "SYNC_SESSION_START",
	6:  "SYNC_SESSION_QUERY",
	7:  "SYNC_SESSION_RESPONSE",
	8:  "SYNC_SESSION_END",
	11: "SYNC_SESSION_GET_BLOCKS",
	12: "SYNC_SESSION_BLOCKS",
	14: "SYNC_SESSION_GET_SNAPSHOT",
	15: "SYNC_SESSION_SNAPSHOT",
	16: "SYNC_SESSION_GET_DELTAS",
	17: "SYNC_SESSION_DELTAS",
}
var SyncMsg_Type_value = map[string]int32{
	"UNDEFINED":                 0,
	"SYNC_STATE_NOTIFY":         1,
	"SYNC_STATE_OPT":            2,
	"SYNC_SESSION_START":        5,
	"SYNC_SESSION_QUERY":        6,
	"SYNC_SESSION_RESPONSE":     7,
	"SYNC_SESSION_END":          8,
	"SYNC_SESSION_GET_BLOCKS":   11,
	"SYNC_SESSION_BLOCKS":       12,
	"SYNC_SESSION_GET_SNAPSHOT": 14,
	"SYNC_SESSION_SNAPSHOT":     15,
	"SYNC_SESSION_GET_DELTAS":   16,
	"SYNC_SESSION_DELTAS":       17,
}

func (x SyncMsg_Type) String() string {
	return proto.EnumName(SyncMsg_Type_name, int32(x))
}
func (SyncMsg_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{25, 0} }

// Transaction defines a function call to a contract.
// `args` is an array of type string so that the chaincode writer can choose
// whatever format they wish for the arguments for their chaincode.
// For example, they may wish to use JSON, XML, or a custom format.
// TODO: Defined remaining fields.
type Transaction struct {
	Type Transaction_Type `protobuf:"varint,1,opt,name=type,enum=protos.Transaction_Type" json:"type,omitempty"`
	// store ChaincodeID as bytes so its encrypted value can be stored
	ChaincodeID                    []byte                     `protobuf:"bytes,2,opt,name=chaincodeID,proto3" json:"chaincodeID,omitempty"`
	Payload                        []byte                     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata                       []byte                     `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Txid                           string                     `protobuf:"bytes,5,opt,name=txid" json:"txid,omitempty"`
	Timestamp                      *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=timestamp" json:"timestamp,omitempty"`
	ConfidentialityLevel           ConfidentialityLevel       `protobuf:"varint,7,opt,name=confidentialityLevel,enum=protos.ConfidentialityLevel" json:"confidentialityLevel,omitempty"`
	ConfidentialityProtocolVersion string                     `protobuf:"bytes,8,opt,name=confidentialityProtocolVersion" json:"confidentialityProtocolVersion,omitempty"`
	Nonce                          []byte                     `protobuf:"bytes,9,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ToValidators                   []byte                     `protobuf:"bytes,10,opt,name=toValidators,proto3" json:"toValidators,omitempty"`
	Cert                           []byte                     `protobuf:"bytes,11,opt,name=cert,proto3" json:"cert,omitempty"`
	Signature                      []byte                     `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Transaction) GetType() Transaction_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_UNDEFINED
}

func (m *Transaction) GetChaincodeID() []byte {
	if m != nil {
		return m.ChaincodeID
	}
	return nil
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Transaction) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Transaction) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Transaction) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Transaction) GetConfidentialityLevel() ConfidentialityLevel {
	if m != nil {
		return m.ConfidentialityLevel
	}
	return ConfidentialityLevel_PUBLIC
}

func (m *Transaction) GetConfidentialityProtocolVersion() string {
	if m != nil {
		return m.ConfidentialityProtocolVersion
	}
	return ""
}

func (m *Transaction) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Transaction) GetToValidators() []byte {
	if m != nil {
		return m.ToValidators
	}
	return nil
}

func (m *Transaction) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// TransactionBlock carries a batch of transactions.
type TransactionBlock struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *TransactionBlock) Reset()                    { *m = TransactionBlock{} }
func (m *TransactionBlock) String() string            { return proto.CompactTextString(m) }
func (*TransactionBlock) ProtoMessage()               {}
func (*TransactionBlock) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *TransactionBlock) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// TransactionResult contains the return value of a transaction. It does
// not track potential state changes that were a result of the transaction.
// txid - The unique identifier of this transaction.
// result - The return value of the transaction.
// errorCode - An error code. 5xx will be logged as a failure in the dashboard.
// error - An error string for logging an issue.
// chaincodeEvent - any event emitted by a transaction
type TransactionResult struct {
	Txid           string          `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Result         []byte          `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ErrorCode      uint32          `protobuf:"varint,3,opt,name=errorCode" json:"errorCode,omitempty"`
	Error          string          `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
	ChaincodeEvent *ChaincodeEvent `protobuf:"bytes,5,opt,name=chaincodeEvent" json:"chaincodeEvent,omitempty"`
}

func (m *TransactionResult) Reset()                    { *m = TransactionResult{} }
func (m *TransactionResult) String() string            { return proto.CompactTextString(m) }
func (*TransactionResult) ProtoMessage()               {}
func (*TransactionResult) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *TransactionResult) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *TransactionResult) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *TransactionResult) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *TransactionResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TransactionResult) GetChaincodeEvent() *ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvent
	}
	return nil
}

// Block carries The data that describes a block in the blockchain.
// version - Version used to track any protocol changes.
// timestamp - The time at which the block or transaction order
// was proposed. This may not be used by all consensus modules.
// transactions - The ordered list of transactions in the block.
// stateHash - The state hash after running transactions in this block.
// previousBlockHash - The hash of the previous block in the chain.
// consensusMetadata - Consensus modules may optionally store any
// additional metadata in this field.
// nonHashData - Data stored with the block, but not included in the blocks
// hash. This allows this data to be different per peer or discarded without
// impacting the blockchain.
type Block struct {
	Version           uint32                     `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Timestamp         *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Transactions      []*Transaction             `protobuf:"bytes,3,rep,name=transactions" json:"transactions,omitempty"`
	StateHash         []byte                     `protobuf:"bytes,4,opt,name=stateHash,proto3" json:"stateHash,omitempty"`
	PreviousBlockHash []byte                     `protobuf:"bytes,5,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
	ConsensusMetadata []byte                     `protobuf:"bytes,6,opt,name=consensusMetadata,proto3" json:"consensusMetadata,omitempty"`
	NonHashData       *NonHashData               `protobuf:"bytes,7,opt,name=nonHashData" json:"nonHashData,omitempty"`
	Txids             []string                   `protobuf:"bytes,8,rep,name=txids" json:"txids,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *Block) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *Block) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

func (m *Block) GetConsensusMetadata() []byte {
	if m != nil {
		return m.ConsensusMetadata
	}
	return nil
}

func (m *Block) GetNonHashData() *NonHashData {
	if m != nil {
		return m.NonHashData
	}
	return nil
}

func (m *Block) GetTxids() []string {
	if m != nil {
		return m.Txids
	}
	return nil
}

// Contains information about the blockchain ledger such as height, current
// block hash, and previous block hash.
type BlockchainInfo struct {
	Height            uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	CurrentBlockHash  []byte `protobuf:"bytes,2,opt,name=currentBlockHash,proto3" json:"currentBlockHash,omitempty"`
	PreviousBlockHash []byte `protobuf:"bytes,3,opt,name=previousBlockHash,proto3" json:"previousBlockHash,omitempty"`
}

func (m *BlockchainInfo) Reset()                    { *m = BlockchainInfo{} }
func (m *BlockchainInfo) String() string            { return proto.CompactTextString(m) }
func (*BlockchainInfo) ProtoMessage()               {}
func (*BlockchainInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *BlockchainInfo) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockchainInfo) GetCurrentBlockHash() []byte {
	if m != nil {
		return m.CurrentBlockHash
	}
	return nil
}

func (m *BlockchainInfo) GetPreviousBlockHash() []byte {
	if m != nil {
		return m.PreviousBlockHash
	}
	return nil
}

// NonHashData is data that is recorded on the block, but not included in
// the block hash when verifying the blockchain.
// localLedgerCommitTimestamp - The time at which the block was added
// to the ledger on the local peer.
// chaincodeEvent - is an array ChaincodeEvents, one per transaction in the
// block
type NonHashData struct {
	LocalLedgerCommitTimestamp *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=localLedgerCommitTimestamp" json:"localLedgerCommitTimestamp,omitempty"`
	ChaincodeEvents            []*ChaincodeEvent          `protobuf:"bytes,2,rep,name=chaincodeEvents" json:"chaincodeEvents,omitempty"`
}

func (m *NonHashData) Reset()                    { *m = NonHashData{} }
func (m *NonHashData) String() string            { return proto.CompactTextString(m) }
func (*NonHashData) ProtoMessage()               {}
func (*NonHashData) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *NonHashData) GetLocalLedgerCommitTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.LocalLedgerCommitTimestamp
	}
	return nil
}

func (m *NonHashData) GetChaincodeEvents() []*ChaincodeEvent {
	if m != nil {
		return m.ChaincodeEvents
	}
	return nil
}

type PeerAddress struct {
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *PeerAddress) Reset()                    { *m = PeerAddress{} }
func (m *PeerAddress) String() string            { return proto.CompactTextString(m) }
func (*PeerAddress) ProtoMessage()               {}
func (*PeerAddress) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *PeerAddress) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PeerAddress) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PeerID struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *PeerID) Reset()                    { *m = PeerID{} }
func (m *PeerID) String() string            { return proto.CompactTextString(m) }
func (*PeerID) ProtoMessage()               {}
func (*PeerID) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *PeerID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PeerEndpoint struct {
	ID      *PeerID           `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Address string            `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Type    PeerEndpoint_Type `protobuf:"varint,3,opt,name=type,enum=protos.PeerEndpoint_Type" json:"type,omitempty"`
	PkiID   []byte            `protobuf:"bytes,4,opt,name=pkiID,proto3" json:"pkiID,omitempty"`
}

func (m *PeerEndpoint) Reset()                    { *m = PeerEndpoint{} }
func (m *PeerEndpoint) String() string            { return proto.CompactTextString(m) }
func (*PeerEndpoint) ProtoMessage()               {}
func (*PeerEndpoint) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *PeerEndpoint) GetID() *PeerID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *PeerEndpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PeerEndpoint) GetType() PeerEndpoint_Type {
	if m != nil {
		return m.Type
	}
	return PeerEndpoint_UNDEFINED
}

func (m *PeerEndpoint) GetPkiID() []byte {
	if m != nil {
		return m.PkiID
	}
	return nil
}

type PeersMessage struct {
	Peers []*PeerEndpoint `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *PeersMessage) Reset()                    { *m = PeersMessage{} }
func (m *PeersMessage) String() string            { return proto.CompactTextString(m) }
func (*PeersMessage) ProtoMessage()               {}
func (*PeersMessage) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *PeersMessage) GetPeers() []*PeerEndpoint {
	if m != nil {
		return m.Peers
	}
	return nil
}

type PeersAddresses struct {
	Addresses []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *PeersAddresses) Reset()                    { *m = PeersAddresses{} }
func (m *PeersAddresses) String() string            { return proto.CompactTextString(m) }
func (*PeersAddresses) ProtoMessage()               {}
func (*PeersAddresses) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *PeersAddresses) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type HelloMessage struct {
	PeerEndpoint   *PeerEndpoint   `protobuf:"bytes,1,opt,name=peerEndpoint" json:"peerEndpoint,omitempty"`
	BlockchainInfo *BlockchainInfo `protobuf:"bytes,2,opt,name=blockchainInfo" json:"blockchainInfo,omitempty"`
}

func (m *HelloMessage) Reset()                    { *m = HelloMessage{} }
func (m *HelloMessage) String() string            { return proto.CompactTextString(m) }
func (*HelloMessage) ProtoMessage()               {}
func (*HelloMessage) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

func (m *HelloMessage) GetPeerEndpoint() *PeerEndpoint {
	if m != nil {
		return m.PeerEndpoint
	}
	return nil
}

func (m *HelloMessage) GetBlockchainInfo() *BlockchainInfo {
	if m != nil {
		return m.BlockchainInfo
	}
	return nil
}

type Gossip struct {
	// all the gossip message (with different catalog) MUST share the
	// same series of seq
	Seq     uint64 `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	Catalog string `protobuf:"bytes,2,opt,name=catalog" json:"catalog,omitempty"`
	// Types that are valid to be assigned to M:
	//	*Gossip_Dig
	//	*Gossip_Ud
	M isGossip_M `protobuf_oneof:"m"`
}

func (m *Gossip) Reset()                    { *m = Gossip{} }
func (m *Gossip) String() string            { return proto.CompactTextString(m) }
func (*Gossip) ProtoMessage()               {}
func (*Gossip) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12} }

type isGossip_M interface {
	isGossip_M()
}

type Gossip_Dig struct {
	Dig *Gossip_Digest `protobuf:"bytes,3,opt,name=dig,oneof"`
}
type Gossip_Ud struct {
	Ud *Gossip_Update `protobuf:"bytes,4,opt,name=ud,oneof"`
}

func (*Gossip_Dig) isGossip_M() {}
func (*Gossip_Ud) isGossip_M()  {}

func (m *Gossip) GetM() isGossip_M {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *Gossip) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Gossip) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

func (m *Gossip) GetDig() *Gossip_Digest {
	if x, ok := m.GetM().(*Gossip_Dig); ok {
		return x.Dig
	}
	return nil
}

func (m *Gossip) GetUd() *Gossip_Update {
	if x, ok := m.GetM().(*Gossip_Ud); ok {
		return x.Ud
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Gossip) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Gossip_OneofMarshaler, _Gossip_OneofUnmarshaler, _Gossip_OneofSizer, []interface{}{
		(*Gossip_Dig)(nil),
		(*Gossip_Ud)(nil),
	}
}

func _Gossip_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Gossip)
	// m
	switch x := m.M.(type) {
	case *Gossip_Dig:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Dig); err != nil {
			return err
		}
	case *Gossip_Ud:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ud); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Gossip.M has unexpected type %T", x)
	}
	return nil
}

func _Gossip_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Gossip)
	switch tag {
	case 3: // m.dig
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Gossip_Digest)
		err := b.DecodeMessage(msg)
		m.M = &Gossip_Dig{msg}
		return true, err
	case 4: // m.ud
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Gossip_Update)
		err := b.DecodeMessage(msg)
		m.M = &Gossip_Ud{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Gossip_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Gossip)
	// m
	switch x := m.M.(type) {
	case *Gossip_Dig:
		s := proto.Size(x.Dig)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Gossip_Ud:
		s := proto.Size(x.Ud)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Gossip_Digest struct {
	// string is used to represent peerID
	Data  map[string]*Gossip_Digest_PeerState `protobuf:"bytes,1,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Epoch []byte                              `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *Gossip_Digest) Reset()                    { *m = Gossip_Digest{} }
func (m *Gossip_Digest) String() string            { return proto.CompactTextString(m) }
func (*Gossip_Digest) ProtoMessage()               {}
func (*Gossip_Digest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12, 0} }

func (m *Gossip_Digest) GetData() map[string]*Gossip_Digest_PeerState {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Gossip_Digest) GetEpoch() []byte {
	if m != nil {
		return m.Epoch
	}
	return nil
}

type Gossip_Digest_PeerState struct {
	State     []byte `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Num       uint64 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Gossip_Digest_PeerState) Reset()                    { *m = Gossip_Digest_PeerState{} }
func (m *Gossip_Digest_PeerState) String() string            { return proto.CompactTextString(m) }
func (*Gossip_Digest_PeerState) ProtoMessage()               {}
func (*Gossip_Digest_PeerState) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12, 0, 0} }

func (m *Gossip_Digest_PeerState) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Gossip_Digest_PeerState) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Gossip_Digest_PeerState) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Gossip_Update struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Gossip_Update) Reset()                    { *m = Gossip_Update{} }
func (m *Gossip_Update) String() string            { return proto.CompactTextString(m) }
func (*Gossip_Update) ProtoMessage()               {}
func (*Gossip_Update) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{12, 1} }

func (m *Gossip_Update) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// TransactionBlock carries a batch of transactions.
type HotTransactionBlock struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	BeginSeries  uint64         `protobuf:"varint,2,opt,name=beginSeries" json:"beginSeries,omitempty"`
}

func (m *HotTransactionBlock) Reset()                    { *m = HotTransactionBlock{} }
func (m *HotTransactionBlock) String() string            { return proto.CompactTextString(m) }
func (*HotTransactionBlock) ProtoMessage()               {}
func (*HotTransactionBlock) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{13} }

func (m *HotTransactionBlock) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *HotTransactionBlock) GetBeginSeries() uint64 {
	if m != nil {
		return m.BeginSeries
	}
	return 0
}

type Gossip_Tx struct {
	Txs map[string]*HotTransactionBlock `protobuf:"bytes,1,rep,name=txs" json:"txs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Gossip_Tx) Reset()                    { *m = Gossip_Tx{} }
func (m *Gossip_Tx) String() string            { return proto.CompactTextString(m) }
func (*Gossip_Tx) ProtoMessage()               {}
func (*Gossip_Tx) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{14} }

func (m *Gossip_Tx) GetTxs() map[string]*HotTransactionBlock {
	if m != nil {
		return m.Txs
	}
	return nil
}

type Message struct {
	Type      Message_Type               `protobuf:"varint,1,opt,name=type,enum=protos.Message_Type" json:"type,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Payload   []byte                     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature []byte                     `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{15} }

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_UNDEFINED
}

func (m *Message) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Response struct {
	Status Response_StatusCode `protobuf:"varint,1,opt,name=status,enum=protos.Response_StatusCode" json:"status,omitempty"`
	Msg    []byte              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{16} }

func (m *Response) GetStatus() Response_StatusCode {
	if m != nil {
		return m.Status
	}
	return Response_UNDEFINED
}

func (m *Response) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type GlobalState struct {
	Count                   uint64   `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	NextNodeStateHash       [][]byte `protobuf:"bytes,3,rep,name=nextNodeStateHash,proto3" json:"nextNodeStateHash,omitempty"`
	ParentNodeStateHash     [][]byte `protobuf:"bytes,4,rep,name=parentNodeStateHash,proto3" json:"parentNodeStateHash,omitempty"`
	LastBranchNodeStateHash []byte   `protobuf:"bytes,5,opt,name=lastBranchNodeStateHash,proto3" json:"lastBranchNodeStateHash,omitempty"`
	NextBranchNodeStateHash []byte   `protobuf:"bytes,7,opt,name=nextBranchNodeStateHash,proto3" json:"nextBranchNodeStateHash,omitempty"`
}

func (m *GlobalState) Reset()                    { *m = GlobalState{} }
func (m *GlobalState) String() string            { return proto.CompactTextString(m) }
func (*GlobalState) ProtoMessage()               {}
func (*GlobalState) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{17} }

func (m *GlobalState) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GlobalState) GetNextNodeStateHash() [][]byte {
	if m != nil {
		return m.NextNodeStateHash
	}
	return nil
}

func (m *GlobalState) GetParentNodeStateHash() [][]byte {
	if m != nil {
		return m.ParentNodeStateHash
	}
	return nil
}

func (m *GlobalState) GetLastBranchNodeStateHash() []byte {
	if m != nil {
		return m.LastBranchNodeStateHash
	}
	return nil
}

func (m *GlobalState) GetNextBranchNodeStateHash() []byte {
	if m != nil {
		return m.NextBranchNodeStateHash
	}
	return nil
}

// BlockState is the payload of Message.SYNC_BLOCK_ADDED. When a VP
// commits a new block to the ledger, it will notify its connected NVPs of the
// block and the delta state. The NVP may call the ledger APIs to apply the
// block and the delta state to its ledger if the block's previousBlockHash
// equals to the NVP's current block hash
type BlockState struct {
	Block      *Block `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
	StateDelta []byte `protobuf:"bytes,2,opt,name=stateDelta,proto3" json:"stateDelta,omitempty"`
}

func (m *BlockState) Reset()                    { *m = BlockState{} }
func (m *BlockState) String() string            { return proto.CompactTextString(m) }
func (*BlockState) ProtoMessage()               {}
func (*BlockState) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{18} }

func (m *BlockState) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockState) GetStateDelta() []byte {
	if m != nil {
		return m.StateDelta
	}
	return nil
}

// SyncBlockRange is the payload of Message.SYNC_GET_BLOCKS, where
// start and end indicate the starting and ending blocks inclusively. The order
// in which blocks are returned is defined by the start and end values. For
// example, if start=3 and end=5, the order of blocks will be 3, 4, 5.
// If start=5 and end=3, the order will be 5, 4, 3.
type SyncBlockRange struct {
	CorrelationId uint64 `protobuf:"varint,1,opt,name=correlationId" json:"correlationId,omitempty"`
	Start         uint64 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End           uint64 `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
}

func (m *SyncBlockRange) Reset()                    { *m = SyncBlockRange{} }
func (m *SyncBlockRange) String() string            { return proto.CompactTextString(m) }
func (*SyncBlockRange) ProtoMessage()               {}
func (*SyncBlockRange) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{19} }

func (m *SyncBlockRange) GetCorrelationId() uint64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *SyncBlockRange) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *SyncBlockRange) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

// SyncBlocks is the payload of Message.SYNC_BLOCKS, where the range
// indicates the blocks responded to the request SYNC_GET_BLOCKS
type SyncBlocks struct {
	Range  *SyncBlockRange `protobuf:"bytes,1,opt,name=range" json:"range,omitempty"`
	Blocks []*Block        `protobuf:"bytes,2,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *SyncBlocks) Reset()                    { *m = SyncBlocks{} }
func (m *SyncBlocks) String() string            { return proto.CompactTextString(m) }
func (*SyncBlocks) ProtoMessage()               {}
func (*SyncBlocks) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{20} }

func (m *SyncBlocks) GetRange() *SyncBlockRange {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *SyncBlocks) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

// SyncSnapshotRequest Payload for the penchainMessage.SYNC_GET_SNAPSHOT message.
type SyncStateSnapshotRequest struct {
	CorrelationId uint64 `protobuf:"varint,1,opt,name=correlationId" json:"correlationId,omitempty"`
}

func (m *SyncStateSnapshotRequest) Reset()                    { *m = SyncStateSnapshotRequest{} }
func (m *SyncStateSnapshotRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncStateSnapshotRequest) ProtoMessage()               {}
func (*SyncStateSnapshotRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{21} }

func (m *SyncStateSnapshotRequest) GetCorrelationId() uint64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

// SyncStateSnapshot is the payload of Message.SYNC_SNAPSHOT, which is a response
// to penchainMessage.SYNC_GET_SNAPSHOT. It contains the snapshot or a chunk of the
// snapshot on stream, and in which case, the sequence indicate the order
// starting at 0.  The terminating message will have len(delta) == 0.
type SyncStateSnapshot struct {
	Delta       []byte                    `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Sequence    uint64                    `protobuf:"varint,2,opt,name=sequence" json:"sequence,omitempty"`
	BlockNumber uint64                    `protobuf:"varint,3,opt,name=blockNumber" json:"blockNumber,omitempty"`
	Request     *SyncStateSnapshotRequest `protobuf:"bytes,4,opt,name=request" json:"request,omitempty"`
}

func (m *SyncStateSnapshot) Reset()                    { *m = SyncStateSnapshot{} }
func (m *SyncStateSnapshot) String() string            { return proto.CompactTextString(m) }
func (*SyncStateSnapshot) ProtoMessage()               {}
func (*SyncStateSnapshot) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{22} }

func (m *SyncStateSnapshot) GetDelta() []byte {
	if m != nil {
		return m.Delta
	}
	return nil
}

func (m *SyncStateSnapshot) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *SyncStateSnapshot) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *SyncStateSnapshot) GetRequest() *SyncStateSnapshotRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

// SyncStateDeltasRequest is the payload of Message.SYNC_GET_STATE.
// blockNumber indicates the block number for the delta which is being
// requested. If no payload is included with SYNC_GET_STATE, it represents
// a request for a snapshot of the current state.
type SyncStateDeltasRequest struct {
	Range *SyncBlockRange `protobuf:"bytes,1,opt,name=range" json:"range,omitempty"`
}

func (m *SyncStateDeltasRequest) Reset()                    { *m = SyncStateDeltasRequest{} }
func (m *SyncStateDeltasRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncStateDeltasRequest) ProtoMessage()               {}
func (*SyncStateDeltasRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{23} }

func (m *SyncStateDeltasRequest) GetRange() *SyncBlockRange {
	if m != nil {
		return m.Range
	}
	return nil
}

// SyncStateDeltas is the payload of the Message.SYNC_STATE in response to
// the Message.SYNC_GET_STATE message.
type SyncStateDeltas struct {
	Range  *SyncBlockRange `protobuf:"bytes,1,opt,name=range" json:"range,omitempty"`
	Deltas [][]byte        `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
}

func (m *SyncStateDeltas) Reset()                    { *m = SyncStateDeltas{} }
func (m *SyncStateDeltas) String() string            { return proto.CompactTextString(m) }
func (*SyncStateDeltas) ProtoMessage()               {}
func (*SyncStateDeltas) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{24} }

func (m *SyncStateDeltas) GetRange() *SyncBlockRange {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *SyncStateDeltas) GetDeltas() [][]byte {
	if m != nil {
		return m.Deltas
	}
	return nil
}

// Like chat, stateSync wrap messages used in a syncing session
type SyncMsg struct {
	Type          SyncMsg_Type `protobuf:"varint,1,opt,name=type,enum=protos.SyncMsg_Type" json:"type,omitempty"`
	CorrelationId uint64       `protobuf:"varint,2,opt,name=correlationId" json:"correlationId,omitempty"`
	Payload       []byte       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *SyncMsg) Reset()                    { *m = SyncMsg{} }
func (m *SyncMsg) String() string            { return proto.CompactTextString(m) }
func (*SyncMsg) ProtoMessage()               {}
func (*SyncMsg) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{25} }

func (m *SyncMsg) GetType() SyncMsg_Type {
	if m != nil {
		return m.Type
	}
	return SyncMsg_UNDEFINED
}

func (m *SyncMsg) GetCorrelationId() uint64 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *SyncMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// //////////////////////////////
type SyncStateQuery struct {
	Id          uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BlockHeight uint64 `protobuf:"varint,2,opt,name=blockHeight" json:"blockHeight,omitempty"`
}

func (m *SyncStateQuery) Reset()                    { *m = SyncStateQuery{} }
func (m *SyncStateQuery) String() string            { return proto.CompactTextString(m) }
func (*SyncStateQuery) ProtoMessage()               {}
func (*SyncStateQuery) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{26} }

func (m *SyncStateQuery) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SyncStateQuery) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type SyncStateResp struct {
	Id          uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Postive     bool   `protobuf:"varint,3,opt,name=postive" json:"postive,omitempty"`
	Statehash   []byte `protobuf:"bytes,4,opt,name=statehash,proto3" json:"statehash,omitempty"`
	BlockHeight uint64 `protobuf:"varint,5,opt,name=blockHeight" json:"blockHeight,omitempty"`
}

func (m *SyncStateResp) Reset()                    { *m = SyncStateResp{} }
func (m *SyncStateResp) String() string            { return proto.CompactTextString(m) }
func (*SyncStateResp) ProtoMessage()               {}
func (*SyncStateResp) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{27} }

func (m *SyncStateResp) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SyncStateResp) GetPostive() bool {
	if m != nil {
		return m.Postive
	}
	return false
}

func (m *SyncStateResp) GetStatehash() []byte {
	if m != nil {
		return m.Statehash
	}
	return nil
}

func (m *SyncStateResp) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Transaction)(nil), "protos.Transaction")
	proto.RegisterType((*TransactionBlock)(nil), "protos.TransactionBlock")
	proto.RegisterType((*TransactionResult)(nil), "protos.TransactionResult")
	proto.RegisterType((*Block)(nil), "protos.Block")
	proto.RegisterType((*BlockchainInfo)(nil), "protos.BlockchainInfo")
	proto.RegisterType((*NonHashData)(nil), "protos.NonHashData")
	proto.RegisterType((*PeerAddress)(nil), "protos.PeerAddress")
	proto.RegisterType((*PeerID)(nil), "protos.PeerID")
	proto.RegisterType((*PeerEndpoint)(nil), "protos.PeerEndpoint")
	proto.RegisterType((*PeersMessage)(nil), "protos.PeersMessage")
	proto.RegisterType((*PeersAddresses)(nil), "protos.PeersAddresses")
	proto.RegisterType((*HelloMessage)(nil), "protos.HelloMessage")
	proto.RegisterType((*Gossip)(nil), "protos.Gossip")
	proto.RegisterType((*Gossip_Digest)(nil), "protos.Gossip.Digest")
	proto.RegisterType((*Gossip_Digest_PeerState)(nil), "protos.Gossip.Digest.PeerState")
	proto.RegisterType((*Gossip_Update)(nil), "protos.Gossip.Update")
	proto.RegisterType((*HotTransactionBlock)(nil), "protos.HotTransactionBlock")
	proto.RegisterType((*Gossip_Tx)(nil), "protos.Gossip_Tx")
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterType((*Response)(nil), "protos.Response")
	proto.RegisterType((*GlobalState)(nil), "protos.GlobalState")
	proto.RegisterType((*BlockState)(nil), "protos.BlockState")
	proto.RegisterType((*SyncBlockRange)(nil), "protos.SyncBlockRange")
	proto.RegisterType((*SyncBlocks)(nil), "protos.SyncBlocks")
	proto.RegisterType((*SyncStateSnapshotRequest)(nil), "protos.SyncStateSnapshotRequest")
	proto.RegisterType((*SyncStateSnapshot)(nil), "protos.SyncStateSnapshot")
	proto.RegisterType((*SyncStateDeltasRequest)(nil), "protos.SyncStateDeltasRequest")
	proto.RegisterType((*SyncStateDeltas)(nil), "protos.SyncStateDeltas")
	proto.RegisterType((*SyncMsg)(nil), "protos.SyncMsg")
	proto.RegisterType((*SyncStateQuery)(nil), "protos.SyncStateQuery")
	proto.RegisterType((*SyncStateResp)(nil), "protos.SyncStateResp")
	proto.RegisterEnum("protos.Transaction_Type", Transaction_Type_name, Transaction_Type_value)
	proto.RegisterEnum("protos.PeerEndpoint_Type", PeerEndpoint_Type_name, PeerEndpoint_Type_value)
	proto.RegisterEnum("protos.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterEnum("protos.Response_StatusCode", Response_StatusCode_name, Response_StatusCode_value)
	proto.RegisterEnum("protos.SyncMsg_Type", SyncMsg_Type_name, SyncMsg_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Peer service

type PeerClient interface {
	// Accepts a stream of Message during chat session, while receiving
	// other Message (e.g. from other peers).
	Chat(ctx context.Context, opts ...grpc.CallOption) (Peer_ChatClient, error)
	// Request a new stream for bi-direction gossip
	// We must sent a peerId first for merging the stream with chatting,
	// This can't be achieve by protobuf and we had to imple it manually
	GossipIn(ctx context.Context, opts ...grpc.CallOption) (Peer_GossipInClient, error)
	// Request a new stream for state syncing
	SyncIn(ctx context.Context, opts ...grpc.CallOption) (Peer_SyncInClient, error)
	// Process a transaction from a remote source.
	ProcessTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error)
}

type peerClient struct {
	cc *grpc.ClientConn
}

func NewPeerClient(cc *grpc.ClientConn) PeerClient {
	return &peerClient{cc}
}

func (c *peerClient) Chat(ctx context.Context, opts ...grpc.CallOption) (Peer_ChatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Peer_serviceDesc.Streams[0], c.cc, "/protos.Peer/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &peerChatClient{stream}
	return x, nil
}

type Peer_ChatClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type peerChatClient struct {
	grpc.ClientStream
}

func (x *peerChatClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *peerChatClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *peerClient) GossipIn(ctx context.Context, opts ...grpc.CallOption) (Peer_GossipInClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Peer_serviceDesc.Streams[1], c.cc, "/protos.Peer/GossipIn", opts...)
	if err != nil {
		return nil, err
	}
	x := &peerGossipInClient{stream}
	return x, nil
}

type Peer_GossipInClient interface {
	Send(*Gossip) error
	Recv() (*Gossip, error)
	grpc.ClientStream
}

type peerGossipInClient struct {
	grpc.ClientStream
}

func (x *peerGossipInClient) Send(m *Gossip) error {
	return x.ClientStream.SendMsg(m)
}

func (x *peerGossipInClient) Recv() (*Gossip, error) {
	m := new(Gossip)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *peerClient) SyncIn(ctx context.Context, opts ...grpc.CallOption) (Peer_SyncInClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Peer_serviceDesc.Streams[2], c.cc, "/protos.Peer/SyncIn", opts...)
	if err != nil {
		return nil, err
	}
	x := &peerSyncInClient{stream}
	return x, nil
}

type Peer_SyncInClient interface {
	Send(*SyncMsg) error
	Recv() (*SyncMsg, error)
	grpc.ClientStream
}

type peerSyncInClient struct {
	grpc.ClientStream
}

func (x *peerSyncInClient) Send(m *SyncMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *peerSyncInClient) Recv() (*SyncMsg, error) {
	m := new(SyncMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *peerClient) ProcessTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/protos.Peer/ProcessTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Peer service

type PeerServer interface {
	// Accepts a stream of Message during chat session, while receiving
	// other Message (e.g. from other peers).
	Chat(Peer_ChatServer) error
	// Request a new stream for bi-direction gossip
	// We must sent a peerId first for merging the stream with chatting,
	// This can't be achieve by protobuf and we had to imple it manually
	GossipIn(Peer_GossipInServer) error
	// Request a new stream for state syncing
	SyncIn(Peer_SyncInServer) error
	// Process a transaction from a remote source.
	ProcessTransaction(context.Context, *Transaction) (*Response, error)
}

func RegisterPeerServer(s *grpc.Server, srv PeerServer) {
	s.RegisterService(&_Peer_serviceDesc, srv)
}

func _Peer_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PeerServer).Chat(&peerChatServer{stream})
}

type Peer_ChatServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type peerChatServer struct {
	grpc.ServerStream
}

func (x *peerChatServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *peerChatServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Peer_GossipIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PeerServer).GossipIn(&peerGossipInServer{stream})
}

type Peer_GossipInServer interface {
	Send(*Gossip) error
	Recv() (*Gossip, error)
	grpc.ServerStream
}

type peerGossipInServer struct {
	grpc.ServerStream
}

func (x *peerGossipInServer) Send(m *Gossip) error {
	return x.ServerStream.SendMsg(m)
}

func (x *peerGossipInServer) Recv() (*Gossip, error) {
	m := new(Gossip)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Peer_SyncIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PeerServer).SyncIn(&peerSyncInServer{stream})
}

type Peer_SyncInServer interface {
	Send(*SyncMsg) error
	Recv() (*SyncMsg, error)
	grpc.ServerStream
}

type peerSyncInServer struct {
	grpc.ServerStream
}

func (x *peerSyncInServer) Send(m *SyncMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *peerSyncInServer) Recv() (*SyncMsg, error) {
	m := new(SyncMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Peer_ProcessTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).ProcessTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Peer/ProcessTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).ProcessTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Peer",
	HandlerType: (*PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTransaction",
			Handler:    _Peer_ProcessTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _Peer_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GossipIn",
			Handler:       _Peer_GossipIn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncIn",
			Handler:       _Peer_SyncIn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fabric.proto",
}

func init() { proto.RegisterFile("fabric.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 2026 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x18, 0x4d, 0x6f, 0x1b, 0x5b,
	0x35, 0xe3, 0xcf, 0xf8, 0xd8, 0x71, 0x26, 0x37, 0x69, 0xea, 0xfa, 0x95, 0xbe, 0x68, 0x00, 0x11,
	0x9e, 0x8a, 0x5f, 0x49, 0x55, 0xb5, 0xaa, 0x04, 0x7a, 0x8e, 0x3d, 0x69, 0xac, 0x26, 0xe3, 0xf4,
	0x8e, 0xd3, 0x47, 0x59, 0x10, 0x4d, 0x3c, 0xb7, 0xce, 0xa8, 0xe3, 0xb9, 0x7e, 0x73, 0xc7, 0x51,
	0xb2, 0x43, 0xac, 0x10, 0x0b, 0xfe, 0x04, 0x4b, 0x96, 0xb0, 0x65, 0x0b, 0xfc, 0x04, 0x10, 0x3f,
	0x82, 0x0d, 0x12, 0x5b, 0x74, 0x3f, 0x66, 0x3c, 0x33, 0x76, 0x1e, 0x2d, 0x62, 0x93, 0xdc, 0xf3,
	0x75, 0xef, 0xf9, 0x3e, 0x67, 0x0c, 0x8d, 0xf7, 0xce, 0x65, 0xe8, 0x8d, 0x3b, 0xb3, 0x90, 0x46,
	0x14, 0x55, 0xc4, 0x3f, 0xd6, 0xde, 0x1c, 0x5f, 0x39, 0x5e, 0x30, 0xa6, 0x2e, 0x91, 0x84, 0xf6,
	0x4e, 0x82, 0x20, 0xd7, 0x24, 0x88, 0x14, 0xf6, 0xf3, 0x09, 0xa5, 0x13, 0x9f, 0x7c, 0x29, 0xa0,
	0xcb, 0xf9, 0xfb, 0x2f, 0x23, 0x6f, 0x4a, 0x58, 0xe4, 0x4c, 0x67, 0x92, 0xc1, 0xf8, 0x5b, 0x09,
	0xea, 0xa3, 0xd0, 0x09, 0x98, 0x33, 0x8e, 0x3c, 0x1a, 0xa0, 0xc7, 0x50, 0x8a, 0x6e, 0x67, 0xa4,
	0xa5, 0xed, 0x69, 0xfb, 0xcd, 0x83, 0x96, 0xe4, 0x62, 0x9d, 0x14, 0x4b, 0x67, 0x74, 0x3b, 0x23,
	0x58, 0x70, 0xa1, 0x3d, 0xa8, 0x27, 0xcf, 0x0e, 0xfa, 0xad, 0xc2, 0x9e, 0xb6, 0xdf, 0xc0, 0x69,
	0x14, 0x6a, 0x41, 0x75, 0xe6, 0xdc, 0xfa, 0xd4, 0x71, 0x5b, 0x45, 0x41, 0x8d, 0x41, 0xd4, 0x86,
	0xf5, 0x29, 0x89, 0x1c, 0xd7, 0x89, 0x9c, 0x56, 0x49, 0x90, 0x12, 0x18, 0x21, 0x28, 0x45, 0x37,
	0x9e, 0xdb, 0x2a, 0xef, 0x69, 0xfb, 0x35, 0x2c, 0xce, 0xe8, 0x05, 0xd4, 0x12, 0xe5, 0x5b, 0x95,
	0x3d, 0x6d, 0xbf, 0x7e, 0xd0, 0xee, 0x48, 0xf3, 0x3a, 0xb1, 0x79, 0x9d, 0x51, 0xcc, 0x81, 0x17,
	0xcc, 0xe8, 0x0c, 0x76, 0xc6, 0x34, 0x78, 0xef, 0xb9, 0x24, 0x88, 0x3c, 0xc7, 0xf7, 0xa2, 0xdb,
	0x13, 0x72, 0x4d, 0xfc, 0x56, 0x55, 0xd8, 0xf8, 0x30, 0xb6, 0xb1, 0xb7, 0x82, 0x07, 0xaf, 0x94,
	0x44, 0x47, 0xf0, 0x28, 0x87, 0x3f, 0xe3, 0x77, 0x8c, 0xa9, 0xff, 0x96, 0x84, 0xcc, 0xa3, 0x41,
	0x6b, 0x5d, 0x68, 0xfe, 0x5f, 0xb8, 0xd0, 0x0e, 0x94, 0x03, 0x1a, 0x8c, 0x49, 0xab, 0x26, 0x1c,
	0x20, 0x01, 0x64, 0x40, 0x23, 0xa2, 0x6f, 0x1d, 0xdf, 0x73, 0x9d, 0x88, 0x86, 0xac, 0x05, 0x82,
	0x98, 0xc1, 0x71, 0x0f, 0x8d, 0x49, 0x18, 0xb5, 0xea, 0x82, 0x26, 0xce, 0xe8, 0x21, 0xd4, 0x98,
	0x37, 0x09, 0x9c, 0x68, 0x1e, 0x92, 0x56, 0x43, 0x10, 0x16, 0x08, 0x83, 0x42, 0x89, 0x47, 0x0e,
	0x6d, 0x40, 0xed, 0xdc, 0xea, 0x9b, 0x47, 0x03, 0xcb, 0xec, 0xeb, 0x6b, 0x68, 0x07, 0xf4, 0xde,
	0x71, 0x77, 0x60, 0xf5, 0x86, 0x7d, 0xf3, 0xa2, 0x6f, 0x9e, 0x9d, 0x0c, 0xdf, 0xe9, 0x5a, 0x16,
	0x3b, 0xb0, 0xde, 0x0e, 0x5f, 0x9b, 0x7a, 0x01, 0x6d, 0xc3, 0xe6, 0x02, 0xfb, 0xe6, 0xdc, 0xc4,
	0xef, 0xf4, 0x22, 0xba, 0x0f, 0xdb, 0x0b, 0xe4, 0xc8, 0xc4, 0xa7, 0x03, 0xab, 0x3b, 0x32, 0xf5,
	0x92, 0xf1, 0x1a, 0xf4, 0x54, 0xda, 0x1c, 0xfa, 0x74, 0xfc, 0x01, 0x3d, 0x87, 0x46, 0xb4, 0xc0,
	0xb1, 0x96, 0xb6, 0x57, 0xdc, 0xaf, 0x1f, 0x6c, 0xaf, 0x48, 0x33, 0x9c, 0x61, 0x34, 0xfe, 0xa0,
	0xc1, 0x56, 0x9a, 0x4a, 0xd8, 0xdc, 0x8f, 0x92, 0x3c, 0xd1, 0x52, 0x79, 0xb2, 0x0b, 0x95, 0x50,
	0x50, 0x55, 0x3a, 0x2a, 0x88, 0x7b, 0x87, 0x84, 0x21, 0x0d, 0x7b, 0xd4, 0x25, 0x22, 0x17, 0x37,
	0xf0, 0x02, 0xc1, 0x23, 0x21, 0x00, 0x91, 0x8a, 0x35, 0x2c, 0x01, 0xf4, 0x53, 0x68, 0x26, 0xc9,
	0x6c, 0xf2, 0xb2, 0x12, 0x19, 0x59, 0x3f, 0xd8, 0x4d, 0x72, 0x26, 0x43, 0xc5, 0x39, 0x6e, 0xe3,
	0x1f, 0x05, 0x28, 0x4b, 0xc3, 0x5b, 0x50, 0xbd, 0x56, 0xa9, 0xa1, 0x89, 0xb7, 0x63, 0x30, 0x9b,
	0xd7, 0x85, 0x4f, 0xc9, 0xeb, 0xbc, 0x33, 0x8b, 0x1f, 0xe9, 0x4c, 0x91, 0x28, 0x91, 0x13, 0x91,
	0x63, 0x87, 0x5d, 0xa9, 0xda, 0x5b, 0x20, 0xd0, 0x63, 0xd8, 0x9a, 0x85, 0xe4, 0xda, 0xa3, 0x73,
	0x26, 0x74, 0x17, 0x5c, 0x65, 0xc1, 0xb5, 0x4c, 0xe0, 0xdc, 0x63, 0x1a, 0x30, 0x12, 0xb0, 0x39,
	0x3b, 0x8d, 0xeb, 0xb9, 0x22, 0xb9, 0x97, 0x08, 0xe8, 0x19, 0xd4, 0x03, 0x1a, 0x70, 0xc1, 0x3e,
	0xe7, 0xab, 0x0a, 0x73, 0x13, 0x8d, 0xad, 0x05, 0x09, 0xa7, 0xf9, 0x78, 0x74, 0x78, 0x6c, 0x59,
	0x6b, 0x7d, 0xaf, 0xc8, 0xa3, 0x23, 0x00, 0xe3, 0x57, 0x1a, 0x34, 0x85, 0x22, 0xc2, 0xeb, 0x83,
	0xe0, 0x3d, 0xe5, 0xc1, 0xbf, 0x22, 0xde, 0xe4, 0x2a, 0x12, 0x5e, 0x2e, 0x61, 0x05, 0xa1, 0x2f,
	0x40, 0x1f, 0xcf, 0xc3, 0x90, 0x04, 0xd1, 0xc2, 0x24, 0x99, 0x1e, 0x4b, 0xf8, 0xd5, 0xf6, 0x17,
	0xef, 0xb0, 0xdf, 0xf8, 0xbd, 0x06, 0xf5, 0x94, 0xde, 0xe8, 0xe7, 0xd0, 0xf6, 0xe9, 0xd8, 0xf1,
	0x4f, 0x88, 0x3b, 0x21, 0x61, 0x8f, 0x4e, 0xa7, 0x5e, 0x94, 0x44, 0x4f, 0x68, 0xf5, 0xed, 0xf1,
	0xfd, 0x16, 0x69, 0xf4, 0x15, 0x6c, 0x66, 0x13, 0x8c, 0xb5, 0x0a, 0x22, 0xe6, 0x77, 0xe5, 0x63,
	0x9e, 0xdd, 0x78, 0x06, 0xf5, 0x33, 0x42, 0xc2, 0xae, 0xeb, 0x86, 0x84, 0x89, 0x2e, 0x72, 0x45,
	0x59, 0x14, 0xd7, 0x0f, 0x3f, 0x73, 0xdc, 0x8c, 0x86, 0xb2, 0x7a, 0xca, 0x58, 0x9c, 0x8d, 0x87,
	0x50, 0xe1, 0x62, 0x83, 0x3e, 0xa7, 0x06, 0xce, 0x94, 0xc4, 0x12, 0xfc, 0x6c, 0xfc, 0x59, 0x83,
	0x06, 0x27, 0x9b, 0x81, 0x3b, 0xa3, 0x5e, 0x10, 0xa1, 0x47, 0x50, 0x18, 0xf4, 0x95, 0xad, 0xcd,
	0x58, 0x35, 0x79, 0x01, 0x2e, 0xc8, 0xa1, 0xe0, 0x48, 0x0d, 0xc4, 0x2b, 0x35, 0x1c, 0x83, 0xe8,
	0x47, 0x6a, 0xfc, 0x14, 0x45, 0x6b, 0x7e, 0x90, 0x96, 0x8d, 0x6f, 0x4f, 0xcf, 0x9f, 0x1d, 0x28,
	0xcf, 0x3e, 0x78, 0x83, 0xbe, 0x4a, 0x62, 0x09, 0x18, 0xcf, 0x57, 0x77, 0xba, 0x0d, 0xa8, 0xbd,
	0xed, 0x9e, 0x0c, 0xfa, 0xdd, 0xd1, 0x10, 0xeb, 0x1a, 0xda, 0x82, 0x0d, 0x6b, 0x68, 0x5d, 0x2c,
	0x50, 0x05, 0xe3, 0xa5, 0xb4, 0x83, 0x9d, 0x12, 0xc6, 0x9c, 0x09, 0x41, 0x5f, 0x40, 0x79, 0xc6,
	0x61, 0xd5, 0xa6, 0x76, 0x56, 0xa9, 0x83, 0x25, 0x8b, 0xd1, 0x81, 0xa6, 0x90, 0x55, 0xae, 0x25,
	0xa2, 0xca, 0x9c, 0x18, 0x10, 0x37, 0xd4, 0xf0, 0x02, 0x61, 0xfc, 0x5a, 0x83, 0xc6, 0x31, 0xf1,
	0x7d, 0x1a, 0x3f, 0xf6, 0x02, 0x1a, 0xb3, 0xd4, 0xbd, 0xca, 0x7d, 0xab, 0xdf, 0xcc, 0x70, 0xf2,
	0x2e, 0x75, 0x99, 0x29, 0x03, 0xd5, 0x46, 0x92, 0xac, 0xc8, 0x16, 0x09, 0xce, 0x71, 0x1b, 0x7f,
	0x2c, 0x42, 0xe5, 0x15, 0x65, 0xcc, 0x9b, 0x21, 0x1d, 0x8a, 0x8c, 0x7c, 0xa3, 0x8a, 0x87, 0x1f,
	0x79, 0xac, 0xc6, 0x4e, 0xe4, 0xf8, 0x74, 0x12, 0xc7, 0x4a, 0x81, 0xe8, 0x87, 0x50, 0x74, 0xbd,
	0x89, 0x08, 0x55, 0xfd, 0xe0, 0x5e, 0xfc, 0x96, 0xbc, 0xa8, 0xd3, 0xf7, 0x26, 0x84, 0x45, 0xc7,
	0x6b, 0x98, 0xf3, 0xa0, 0x1f, 0x40, 0x61, 0xee, 0x8a, 0x20, 0x2d, 0x73, 0x9e, 0xcf, 0x5c, 0xde,
	0x79, 0xd6, 0x70, 0x61, 0xee, 0xb6, 0x7f, 0x59, 0x80, 0x8a, 0x14, 0x45, 0x4f, 0xa1, 0x24, 0x7a,
	0x89, 0xf4, 0xfd, 0xe7, 0x2b, 0xef, 0xef, 0xf0, 0x92, 0x33, 0x83, 0x28, 0xbc, 0xc5, 0x82, 0x59,
	0xb4, 0xf1, 0x19, 0x1d, 0xc7, 0xc5, 0x2d, 0x81, 0xf6, 0x1b, 0xa8, 0x71, 0xf7, 0xd9, 0xbc, 0xc5,
	0x71, 0x16, 0xd1, 0xeb, 0x84, 0x91, 0x0d, 0x2c, 0x01, 0x6e, 0x78, 0x30, 0x9f, 0x0a, 0xb1, 0x12,
	0xe6, 0xc7, 0xec, 0x34, 0x2d, 0xe7, 0xa6, 0x69, 0xfb, 0x67, 0x50, 0x4b, 0xde, 0xe6, 0xc2, 0x1f,
	0xc8, 0xad, 0xaa, 0x09, 0x7e, 0x44, 0xcf, 0xa0, 0x7c, 0xed, 0xf8, 0x73, 0xa2, 0x22, 0x71, 0x87,
	0xf6, 0x89, 0x52, 0x58, 0x72, 0xbf, 0x2c, 0xbc, 0xd0, 0xda, 0x06, 0x54, 0xa4, 0x4b, 0xd2, 0xbb,
	0x93, 0x96, 0xd9, 0x9d, 0x0e, 0x8b, 0xa0, 0x4d, 0x8d, 0x19, 0x6c, 0x1f, 0xd3, 0xe8, 0xff, 0x36,
	0x62, 0xf9, 0x32, 0x77, 0x49, 0x26, 0x5e, 0x60, 0x93, 0xd0, 0x23, 0x4c, 0xb9, 0x22, 0x8d, 0x32,
	0x7e, 0xab, 0x41, 0x4d, 0x5a, 0x70, 0x31, 0xba, 0x41, 0x8f, 0xa1, 0x18, 0xdd, 0xc4, 0xf7, 0xb7,
	0xb3, 0x16, 0x5e, 0x8c, 0x6e, 0x3a, 0xa3, 0x1b, 0x26, 0x43, 0xc3, 0xd9, 0xda, 0x36, 0xac, 0xc7,
	0x88, 0x15, 0xfe, 0xfa, 0x71, 0xd6, 0x5f, 0x9f, 0xc5, 0xb7, 0xad, 0x30, 0x30, 0xe5, 0x2b, 0xe3,
	0x9f, 0x45, 0xa8, 0xc6, 0xf5, 0xb3, 0x9f, 0xd9, 0x5c, 0x93, 0xba, 0x51, 0xe4, 0x74, 0xd7, 0xf8,
	0xdf, 0x27, 0xee, 0xdd, 0xdb, 0x6c, 0x26, 0x5b, 0x4a, 0xf9, 0xdd, 0xeb, 0x2f, 0x85, 0xd5, 0x2d,
	0xa9, 0x09, 0xd0, 0x1f, 0xd8, 0xbd, 0x8b, 0x63, 0xf3, 0xe4, 0x64, 0xa8, 0x6b, 0x7c, 0xc1, 0x12,
	0x30, 0xff, 0x33, 0xb4, 0x2c, 0xb3, 0x37, 0xd2, 0x0b, 0x08, 0x41, 0x53, 0x20, 0x5f, 0x99, 0xa3,
	0x8b, 0x33, 0xd3, 0xc4, 0xb6, 0x5e, 0x4c, 0x04, 0x25, 0x5c, 0x42, 0x9b, 0x50, 0x17, 0xb0, 0x65,
	0x7e, 0x7d, 0x6a, 0xbf, 0xd2, 0xcb, 0xe8, 0x1e, 0x6c, 0x89, 0xad, 0xec, 0x62, 0x84, 0xbb, 0x96,
	0xdd, 0xed, 0x8d, 0x06, 0x43, 0x4b, 0xaf, 0xf0, 0x07, 0xec, 0x77, 0x96, 0xbc, 0xeb, 0xf0, 0x64,
	0xd8, 0x7b, 0x6d, 0xeb, 0x75, 0x2e, 0x2c, 0x90, 0x0a, 0xd1, 0xe0, 0xdb, 0xdf, 0x02, 0x71, 0xd1,
	0xed, 0xf7, 0xcd, 0xbe, 0xbe, 0x81, 0x3e, 0x83, 0xfb, 0x02, 0x6b, 0x8f, 0xba, 0x23, 0x53, 0xdc,
	0x60, 0x5b, 0xdd, 0x33, 0xfb, 0x78, 0x38, 0xd2, 0x9b, 0x7c, 0x0b, 0x4c, 0x11, 0x13, 0xc2, 0x26,
	0x7a, 0x00, 0xf7, 0x72, 0x52, 0x7d, 0xf3, 0x64, 0xd4, 0xb5, 0x75, 0x9d, 0xeb, 0x98, 0x22, 0x29,
	0xf4, 0x16, 0x6a, 0xc0, 0x3a, 0x36, 0xed, 0xb3, 0xa1, 0x65, 0x9b, 0xfa, 0x0e, 0xf7, 0x58, 0x8f,
	0x1f, 0x2d, 0xfb, 0xdc, 0xd6, 0xef, 0x19, 0xbf, 0xd1, 0x60, 0x1d, 0x13, 0x36, 0xe3, 0x9b, 0x05,
	0x7a, 0x0a, 0x15, 0x5e, 0xbd, 0x73, 0xa6, 0x82, 0x9e, 0xa4, 0x4d, 0xcc, 0xd1, 0xb1, 0x05, 0x99,
	0x6f, 0x78, 0x58, 0xb1, 0xf2, 0xe4, 0x9b, 0xb2, 0x89, 0x6a, 0x10, 0xfc, 0x68, 0x3c, 0x07, 0x58,
	0xf0, 0xe5, 0x43, 0xd4, 0x80, 0xaa, 0x7d, 0xde, 0xeb, 0x99, 0xb6, 0xad, 0xff, 0x55, 0xe3, 0xd0,
	0x51, 0x77, 0x70, 0x72, 0x8e, 0x4d, 0xfd, 0x5f, 0x45, 0xe3, 0xdf, 0x1a, 0xd4, 0x5f, 0xf9, 0xf4,
	0xd2, 0xf1, 0x93, 0xd6, 0x32, 0xa6, 0xf3, 0x20, 0x5e, 0x3e, 0x24, 0xc0, 0xf7, 0x89, 0x80, 0xdc,
	0x44, 0x16, 0x75, 0x89, 0x9d, 0x6c, 0x5d, 0x7c, 0x57, 0x6b, 0xe0, 0x65, 0x02, 0x7a, 0x02, 0xdb,
	0x33, 0x87, 0x2f, 0x24, 0x59, 0xfe, 0x92, 0xe0, 0x5f, 0x45, 0x42, 0x2f, 0xe0, 0xbe, 0xef, 0xb0,
	0xe8, 0x30, 0x74, 0x82, 0xf1, 0x55, 0x56, 0x4a, 0xb6, 0xad, 0xbb, 0xc8, 0x5c, 0x92, 0x2b, 0xb0,
	0x4a, 0xb2, 0x2a, 0x25, 0xef, 0x20, 0x1b, 0x6f, 0x00, 0x44, 0x31, 0x4a, 0xbb, 0xbf, 0x0b, 0x65,
	0x31, 0x52, 0xd4, 0xcc, 0xda, 0xc8, 0xcc, 0x1d, 0x2c, 0x69, 0xe8, 0x11, 0x80, 0x68, 0xb5, 0x7d,
	0xe2, 0x47, 0x8e, 0x72, 0x7f, 0x0a, 0x63, 0xfc, 0x02, 0x9a, 0xf6, 0x6d, 0x30, 0x96, 0x32, 0x4e,
	0x30, 0x21, 0xe8, 0x7b, 0xb0, 0x31, 0xa6, 0x61, 0x48, 0x7c, 0x87, 0x17, 0xff, 0xc0, 0x55, 0x6e,
	0xcd, 0x22, 0x55, 0x3f, 0x57, 0x0b, 0x4b, 0x09, 0x4b, 0x80, 0x47, 0x99, 0x04, 0xb2, 0x4a, 0x4b,
	0x98, 0x1f, 0x0d, 0x07, 0x20, 0xb9, 0x9f, 0xa1, 0xc7, 0x50, 0x0e, 0xf9, 0x23, 0x4a, 0xe5, 0x64,
	0x54, 0x66, 0x55, 0xc0, 0x92, 0x09, 0x7d, 0x1f, 0x2a, 0xc2, 0x88, 0x78, 0xdf, 0xca, 0x59, 0xa8,
	0x88, 0xc6, 0x57, 0xd0, 0xe2, 0xf2, 0xc2, 0x29, 0x76, 0xe0, 0xcc, 0xd8, 0x15, 0x8d, 0x30, 0xf9,
	0x66, 0xce, 0xc7, 0xd9, 0x47, 0x19, 0x63, 0xfc, 0x4e, 0x83, 0xad, 0xa5, 0x2b, 0xb8, 0x89, 0xae,
	0xf0, 0x9a, 0x1a, 0x59, 0x02, 0xe0, 0x1f, 0xd0, 0x8c, 0x5f, 0xce, 0xbf, 0x1f, 0xa5, 0xed, 0x09,
	0x2c, 0x7a, 0x39, 0xd7, 0xc9, 0x9a, 0x4f, 0x2f, 0x49, 0xa8, 0xdc, 0x90, 0x46, 0xa1, 0x97, 0x50,
	0x0d, 0xa5, 0x6a, 0x6a, 0x2e, 0xef, 0xa5, 0x5d, 0xb0, 0xca, 0x04, 0x1c, 0x0b, 0x18, 0x47, 0xb0,
	0x9b, 0x30, 0x89, 0xe0, 0xb1, 0xd8, 0xca, 0x4f, 0x72, 0xab, 0xf1, 0x35, 0x6c, 0xe6, 0xee, 0xf9,
	0xc4, 0xb8, 0xec, 0x42, 0x45, 0xf8, 0x42, 0xc6, 0xa5, 0x81, 0x15, 0x64, 0xfc, 0xa9, 0x08, 0x55,
	0x2e, 0x71, 0xca, 0x26, 0x77, 0xcd, 0x05, 0x45, 0x4e, 0xcf, 0x85, 0xa5, 0x10, 0x15, 0x56, 0xe5,
	0xdb, 0x9d, 0x33, 0xe0, 0xce, 0x2e, 0x9f, 0xed, 0x73, 0xd6, 0x70, 0x34, 0x38, 0xe2, 0xdf, 0xd8,
	0x08, 0x9a, 0x29, 0xf4, 0xf0, 0x8c, 0xf7, 0xfa, 0x5d, 0x40, 0x12, 0x67, 0xda, 0xf6, 0x60, 0x68,
	0x71, 0x1a, 0x1e, 0xe9, 0xe5, 0x25, 0xbc, 0xfc, 0xf8, 0xae, 0x2c, 0xba, 0xab, 0xc2, 0x27, 0x8d,
	0xb3, 0x9a, 0x34, 0xf1, 0x98, 0x64, 0x5a, 0x7d, 0x7d, 0x7d, 0xd1, 0xc4, 0x15, 0x36, 0x33, 0x08,
	0x92, 0x26, 0xae, 0x88, 0xc9, 0x40, 0xf8, 0x0e, 0x3c, 0x58, 0x92, 0x4a, 0x35, 0xff, 0xbc, 0x16,
	0xa9, 0xf6, 0xbf, 0xea, 0xbd, 0x64, 0x00, 0xe4, 0xdf, 0x8b, 0x47, 0x80, 0x71, 0x28, 0x7b, 0x81,
	0x48, 0x8c, 0x37, 0x73, 0x12, 0xde, 0xa2, 0x26, 0x14, 0xd4, 0x77, 0xfe, 0x06, 0x2e, 0x78, 0x6e,
	0x92, 0xe0, 0xc7, 0xf2, 0x6b, 0xaf, 0x90, 0x4a, 0x70, 0x89, 0x32, 0x6e, 0x61, 0x23, 0xb9, 0x83,
	0xcf, 0x83, 0xa5, 0x2b, 0x78, 0x20, 0x29, 0x8b, 0xbc, 0x6b, 0xf9, 0xb9, 0xb1, 0x8e, 0x63, 0x30,
	0xf9, 0x3e, 0xbe, 0xca, 0x7f, 0x1f, 0x73, 0x44, 0xfe, 0xe9, 0xf2, 0xd2, 0xd3, 0x07, 0x7f, 0xd7,
	0xa0, 0xc4, 0x77, 0x3b, 0xd4, 0x81, 0x52, 0xef, 0xca, 0x89, 0xd0, 0x66, 0x6e, 0x1b, 0x69, 0xe7,
	0x11, 0xc6, 0xda, 0xbe, 0xf6, 0x44, 0x43, 0x4f, 0x60, 0x5d, 0xee, 0x4f, 0x83, 0x00, 0x35, 0xb3,
	0x1b, 0x55, 0x3b, 0x07, 0x27, 0x12, 0x15, 0x6e, 0xe5, 0x20, 0x58, 0xbc, 0xa1, 0x32, 0xbb, 0x9d,
	0x47, 0x28, 0x89, 0x9f, 0x00, 0x3a, 0x0b, 0xe9, 0x98, 0x30, 0x96, 0xfe, 0xdd, 0x6f, 0xd5, 0x7e,
	0xd8, 0xd6, 0xf3, 0xf3, 0xd4, 0x58, 0xbb, 0x94, 0x3f, 0x40, 0x3e, 0xfd, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xed, 0x13, 0x30, 0x8e, 0x97, 0x14, 0x00, 0x00,
}
