package protos

import (
	grpc "google.golang.org/grpc"
)

//we extended the gossipin handler generated by protobuf,
//this code suppose some content so we may also updated it if protobuf is updated
//current protobuf these codes worked under was 3.3
func InitGossipClient(in *PeerID, x grpc.ClientStream) error {

	if err := x.SendMsg(in); err != nil {
		return err
	}
	return nil
}

func GossipServInit(x grpc.ServerStream) (*PeerID, error) {
	m := new(PeerID)
	if err := x.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
