// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gossip.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GossipMsg struct {
	// all the gossip message (with different catalog) MUST share the
	// same series of seq
	Seq     uint64 `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	Catalog string `protobuf:"bytes,2,opt,name=catalog" json:"catalog,omitempty"`
	// Types that are valid to be assigned to M:
	//	*GossipMsg_Dig
	//	*GossipMsg_Ud
	M isGossipMsg_M `protobuf_oneof:"m"`
}

func (m *GossipMsg) Reset()                    { *m = GossipMsg{} }
func (m *GossipMsg) String() string            { return proto.CompactTextString(m) }
func (*GossipMsg) ProtoMessage()               {}
func (*GossipMsg) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type isGossipMsg_M interface {
	isGossipMsg_M()
}

type GossipMsg_Dig struct {
	Dig *GossipMsg_Digest `protobuf:"bytes,3,opt,name=dig,oneof"`
}
type GossipMsg_Ud struct {
	Ud *GossipMsg_Update `protobuf:"bytes,4,opt,name=ud,oneof"`
}

func (*GossipMsg_Dig) isGossipMsg_M() {}
func (*GossipMsg_Ud) isGossipMsg_M()  {}

func (m *GossipMsg) GetM() isGossipMsg_M {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *GossipMsg) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *GossipMsg) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

func (m *GossipMsg) GetDig() *GossipMsg_Digest {
	if x, ok := m.GetM().(*GossipMsg_Dig); ok {
		return x.Dig
	}
	return nil
}

func (m *GossipMsg) GetUd() *GossipMsg_Update {
	if x, ok := m.GetM().(*GossipMsg_Ud); ok {
		return x.Ud
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GossipMsg) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GossipMsg_OneofMarshaler, _GossipMsg_OneofUnmarshaler, _GossipMsg_OneofSizer, []interface{}{
		(*GossipMsg_Dig)(nil),
		(*GossipMsg_Ud)(nil),
	}
}

func _GossipMsg_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GossipMsg)
	// m
	switch x := m.M.(type) {
	case *GossipMsg_Dig:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Dig); err != nil {
			return err
		}
	case *GossipMsg_Ud:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ud); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GossipMsg.M has unexpected type %T", x)
	}
	return nil
}

func _GossipMsg_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GossipMsg)
	switch tag {
	case 3: // m.dig
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GossipMsg_Digest)
		err := b.DecodeMessage(msg)
		m.M = &GossipMsg_Dig{msg}
		return true, err
	case 4: // m.ud
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GossipMsg_Update)
		err := b.DecodeMessage(msg)
		m.M = &GossipMsg_Ud{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GossipMsg_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GossipMsg)
	// m
	switch x := m.M.(type) {
	case *GossipMsg_Dig:
		s := proto.Size(x.Dig)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GossipMsg_Ud:
		s := proto.Size(x.Ud)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GossipMsg_Digest struct {
	// Types that are valid to be assigned to D:
	//	*GossipMsg_Digest_Peer
	//	*GossipMsg_Digest_Tx
	D      isGossipMsg_Digest_D `protobuf_oneof:"d"`
	NoResp bool                 `protobuf:"varint,4,opt,name=noResp" json:"noResp,omitempty"`
}

func (m *GossipMsg_Digest) Reset()                    { *m = GossipMsg_Digest{} }
func (m *GossipMsg_Digest) String() string            { return proto.CompactTextString(m) }
func (*GossipMsg_Digest) ProtoMessage()               {}
func (*GossipMsg_Digest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0, 0} }

type isGossipMsg_Digest_D interface {
	isGossipMsg_Digest_D()
}

type GossipMsg_Digest_Peer struct {
	Peer *GossipMsg_Digest_PeerStates `protobuf:"bytes,6,opt,name=peer,oneof"`
}
type GossipMsg_Digest_Tx struct {
	Tx *GossipMsg_Digest_TxStates `protobuf:"bytes,7,opt,name=tx,oneof"`
}

func (*GossipMsg_Digest_Peer) isGossipMsg_Digest_D() {}
func (*GossipMsg_Digest_Tx) isGossipMsg_Digest_D()   {}

func (m *GossipMsg_Digest) GetD() isGossipMsg_Digest_D {
	if m != nil {
		return m.D
	}
	return nil
}

func (m *GossipMsg_Digest) GetPeer() *GossipMsg_Digest_PeerStates {
	if x, ok := m.GetD().(*GossipMsg_Digest_Peer); ok {
		return x.Peer
	}
	return nil
}

func (m *GossipMsg_Digest) GetTx() *GossipMsg_Digest_TxStates {
	if x, ok := m.GetD().(*GossipMsg_Digest_Tx); ok {
		return x.Tx
	}
	return nil
}

func (m *GossipMsg_Digest) GetNoResp() bool {
	if m != nil {
		return m.NoResp
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GossipMsg_Digest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GossipMsg_Digest_OneofMarshaler, _GossipMsg_Digest_OneofUnmarshaler, _GossipMsg_Digest_OneofSizer, []interface{}{
		(*GossipMsg_Digest_Peer)(nil),
		(*GossipMsg_Digest_Tx)(nil),
	}
}

func _GossipMsg_Digest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GossipMsg_Digest)
	// d
	switch x := m.D.(type) {
	case *GossipMsg_Digest_Peer:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Peer); err != nil {
			return err
		}
	case *GossipMsg_Digest_Tx:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tx); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GossipMsg_Digest.D has unexpected type %T", x)
	}
	return nil
}

func _GossipMsg_Digest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GossipMsg_Digest)
	switch tag {
	case 6: // d.peer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GossipMsg_Digest_PeerStates)
		err := b.DecodeMessage(msg)
		m.D = &GossipMsg_Digest_Peer{msg}
		return true, err
	case 7: // d.tx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GossipMsg_Digest_TxStates)
		err := b.DecodeMessage(msg)
		m.D = &GossipMsg_Digest_Tx{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GossipMsg_Digest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GossipMsg_Digest)
	// d
	switch x := m.D.(type) {
	case *GossipMsg_Digest_Peer:
		s := proto.Size(x.Peer)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GossipMsg_Digest_Tx:
		s := proto.Size(x.Tx)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GossipMsg_Digest_PeerState struct {
	State    []byte `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Num      uint64 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	PeerName string `protobuf:"bytes,3,opt,name=peerName" json:"peerName,omitempty"`
}

func (m *GossipMsg_Digest_PeerState) Reset()         { *m = GossipMsg_Digest_PeerState{} }
func (m *GossipMsg_Digest_PeerState) String() string { return proto.CompactTextString(m) }
func (*GossipMsg_Digest_PeerState) ProtoMessage()    {}
func (*GossipMsg_Digest_PeerState) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{0, 0, 0}
}

func (m *GossipMsg_Digest_PeerState) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GossipMsg_Digest_PeerState) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *GossipMsg_Digest_PeerState) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

type GossipMsg_Digest_PeerStates struct {
	Epoch  []byte                        `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	IsFull bool                          `protobuf:"varint,2,opt,name=isFull" json:"isFull,omitempty"`
	PeerD  []*GossipMsg_Digest_PeerState `protobuf:"bytes,3,rep,name=peerD" json:"peerD,omitempty"`
}

func (m *GossipMsg_Digest_PeerStates) Reset()         { *m = GossipMsg_Digest_PeerStates{} }
func (m *GossipMsg_Digest_PeerStates) String() string { return proto.CompactTextString(m) }
func (*GossipMsg_Digest_PeerStates) ProtoMessage()    {}
func (*GossipMsg_Digest_PeerStates) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{0, 0, 1}
}

func (m *GossipMsg_Digest_PeerStates) GetEpoch() []byte {
	if m != nil {
		return m.Epoch
	}
	return nil
}

func (m *GossipMsg_Digest_PeerStates) GetIsFull() bool {
	if m != nil {
		return m.IsFull
	}
	return false
}

func (m *GossipMsg_Digest_PeerStates) GetPeerD() []*GossipMsg_Digest_PeerState {
	if m != nil {
		return m.PeerD
	}
	return nil
}

type GossipMsg_Digest_TxStates struct {
	TxID []string `protobuf:"bytes,1,rep,name=txID" json:"txID,omitempty"`
}

func (m *GossipMsg_Digest_TxStates) Reset()                    { *m = GossipMsg_Digest_TxStates{} }
func (m *GossipMsg_Digest_TxStates) String() string            { return proto.CompactTextString(m) }
func (*GossipMsg_Digest_TxStates) ProtoMessage()               {}
func (*GossipMsg_Digest_TxStates) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0, 0, 2} }

func (m *GossipMsg_Digest_TxStates) GetTxID() []string {
	if m != nil {
		return m.TxID
	}
	return nil
}

type GossipMsg_Update struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *GossipMsg_Update) Reset()                    { *m = GossipMsg_Update{} }
func (m *GossipMsg_Update) String() string            { return proto.CompactTextString(m) }
func (*GossipMsg_Update) ProtoMessage()               {}
func (*GossipMsg_Update) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0, 1} }

func (m *GossipMsg_Update) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// TransactionBlock carries a batch of transactions.
type HotTransactionBlock struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	BeginSeries  uint64         `protobuf:"varint,2,opt,name=beginSeries" json:"beginSeries,omitempty"`
}

func (m *HotTransactionBlock) Reset()                    { *m = HotTransactionBlock{} }
func (m *HotTransactionBlock) String() string            { return proto.CompactTextString(m) }
func (*HotTransactionBlock) ProtoMessage()               {}
func (*HotTransactionBlock) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *HotTransactionBlock) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *HotTransactionBlock) GetBeginSeries() uint64 {
	if m != nil {
		return m.BeginSeries
	}
	return 0
}

type PeerTxState struct {
	Digest         []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Num            uint64 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	Signature      []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Endorsement    []byte `protobuf:"bytes,6,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
	EndorsementVer uint32 `protobuf:"varint,7,opt,name=endorsementVer" json:"endorsementVer,omitempty"`
}

func (m *PeerTxState) Reset()                    { *m = PeerTxState{} }
func (m *PeerTxState) String() string            { return proto.CompactTextString(m) }
func (*PeerTxState) ProtoMessage()               {}
func (*PeerTxState) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *PeerTxState) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *PeerTxState) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *PeerTxState) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PeerTxState) GetEndorsement() []byte {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

func (m *PeerTxState) GetEndorsementVer() uint32 {
	if m != nil {
		return m.EndorsementVer
	}
	return 0
}

type Gossip_Tx struct {
	Txs map[string]*HotTransactionBlock `protobuf:"bytes,1,rep,name=txs" json:"txs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Gossip_Tx) Reset()                    { *m = Gossip_Tx{} }
func (m *Gossip_Tx) String() string            { return proto.CompactTextString(m) }
func (*Gossip_Tx) ProtoMessage()               {}
func (*Gossip_Tx) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *Gossip_Tx) GetTxs() map[string]*HotTransactionBlock {
	if m != nil {
		return m.Txs
	}
	return nil
}

type Gossip_TxState struct {
	Txs map[string]*PeerTxState `protobuf:"bytes,1,rep,name=txs" json:"txs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Gossip_TxState) Reset()                    { *m = Gossip_TxState{} }
func (m *Gossip_TxState) String() string            { return proto.CompactTextString(m) }
func (*Gossip_TxState) ProtoMessage()               {}
func (*Gossip_TxState) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *Gossip_TxState) GetTxs() map[string]*PeerTxState {
	if m != nil {
		return m.Txs
	}
	return nil
}

func init() {
	proto.RegisterType((*GossipMsg)(nil), "protos.GossipMsg")
	proto.RegisterType((*GossipMsg_Digest)(nil), "protos.GossipMsg.Digest")
	proto.RegisterType((*GossipMsg_Digest_PeerState)(nil), "protos.GossipMsg.Digest.PeerState")
	proto.RegisterType((*GossipMsg_Digest_PeerStates)(nil), "protos.GossipMsg.Digest.PeerStates")
	proto.RegisterType((*GossipMsg_Digest_TxStates)(nil), "protos.GossipMsg.Digest.TxStates")
	proto.RegisterType((*GossipMsg_Update)(nil), "protos.GossipMsg.Update")
	proto.RegisterType((*HotTransactionBlock)(nil), "protos.HotTransactionBlock")
	proto.RegisterType((*PeerTxState)(nil), "protos.PeerTxState")
	proto.RegisterType((*Gossip_Tx)(nil), "protos.Gossip_Tx")
	proto.RegisterType((*Gossip_TxState)(nil), "protos.Gossip_TxState")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Gossip service

type GossipClient interface {
	// Request a new stream for bi-direction gossip
	// We must sent a peerId first for merging the stream with chatting,
	// This can't be achieve by protobuf and we had to imple it manually
	In(ctx context.Context, opts ...grpc.CallOption) (Gossip_InClient, error)
}

type gossipClient struct {
	cc *grpc.ClientConn
}

func NewGossipClient(cc *grpc.ClientConn) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) In(ctx context.Context, opts ...grpc.CallOption) (Gossip_InClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Gossip_serviceDesc.Streams[0], c.cc, "/protos.Gossip/In", opts...)
	if err != nil {
		return nil, err
	}
	x := &gossipInClient{stream}
	return x, nil
}

type Gossip_InClient interface {
	Send(*GossipMsg) error
	Recv() (*GossipMsg, error)
	grpc.ClientStream
}

type gossipInClient struct {
	grpc.ClientStream
}

func (x *gossipInClient) Send(m *GossipMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gossipInClient) Recv() (*GossipMsg, error) {
	m := new(GossipMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Gossip service

type GossipServer interface {
	// Request a new stream for bi-direction gossip
	// We must sent a peerId first for merging the stream with chatting,
	// This can't be achieve by protobuf and we had to imple it manually
	In(Gossip_InServer) error
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_In_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GossipServer).In(&gossipInServer{stream})
}

type Gossip_InServer interface {
	Send(*GossipMsg) error
	Recv() (*GossipMsg, error)
	grpc.ServerStream
}

type gossipInServer struct {
	grpc.ServerStream
}

func (x *gossipInServer) Send(m *GossipMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gossipInServer) Recv() (*GossipMsg, error) {
	m := new(GossipMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "In",
			Handler:       _Gossip_In_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gossip.proto",
}

func init() { proto.RegisterFile("gossip.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xcd, 0xda, 0x8e, 0x1b, 0x8f, 0xf3, 0x55, 0x1f, 0x5b, 0x84, 0x2c, 0x83, 0xc0, 0x18, 0x09,
	0x19, 0x84, 0xa2, 0x36, 0xbd, 0xa0, 0xf4, 0xb2, 0x2a, 0x90, 0x0a, 0xf1, 0xa3, 0x6d, 0xe0, 0xb6,
	0xda, 0xc6, 0x8b, 0xb1, 0xea, 0xd8, 0xc6, 0xbb, 0x46, 0xee, 0x4b, 0x20, 0xde, 0x80, 0xe7, 0xe0,
	0xdd, 0xb8, 0x40, 0xbb, 0xfe, 0xa9, 0xd3, 0x34, 0x70, 0x95, 0x39, 0xa3, 0x33, 0x33, 0x67, 0xce,
	0xac, 0x03, 0xe3, 0x28, 0xe3, 0x3c, 0xce, 0x27, 0x79, 0x91, 0x89, 0x0c, 0x9b, 0xea, 0x87, 0xbb,
	0xe3, 0xcf, 0xf4, 0xbc, 0x88, 0x17, 0x75, 0xd6, 0xff, 0x65, 0x80, 0xf5, 0x5a, 0xd1, 0xde, 0xf2,
	0x08, 0xff, 0x0f, 0x3a, 0x67, 0x5f, 0x1d, 0xe4, 0xa1, 0xc0, 0x20, 0x32, 0xc4, 0x0e, 0x6c, 0x2d,
	0xa8, 0xa0, 0x49, 0x16, 0x39, 0x9a, 0x87, 0x02, 0x8b, 0xb4, 0x10, 0x3f, 0x03, 0x3d, 0x8c, 0x23,
	0x47, 0xf7, 0x50, 0x60, 0x4f, 0x9d, 0xba, 0x1d, 0x9f, 0x74, 0xbd, 0x26, 0xc7, 0x71, 0xc4, 0xb8,
	0x98, 0x0d, 0x88, 0xa4, 0xe1, 0xa7, 0xa0, 0x95, 0xa1, 0x63, 0x6c, 0x22, 0x7f, 0xcc, 0x43, 0x2a,
	0xd8, 0x6c, 0x40, 0xb4, 0x32, 0x74, 0x7f, 0x6b, 0x60, 0xd6, 0xd5, 0xf8, 0x05, 0x18, 0x39, 0x63,
	0x85, 0x63, 0xaa, 0xc2, 0x47, 0x9b, 0xa6, 0x4c, 0x3e, 0x30, 0x56, 0x9c, 0x0a, 0x2a, 0x18, 0x9f,
	0x0d, 0x88, 0x2a, 0xc1, 0xfb, 0xa0, 0x89, 0xca, 0xd9, 0x52, 0x85, 0x0f, 0x37, 0x16, 0xce, 0xab,
	0xae, 0x4c, 0x13, 0x15, 0xbe, 0x03, 0x66, 0x9a, 0x11, 0xc6, 0x73, 0x25, 0x75, 0x44, 0x1a, 0xe4,
	0xbe, 0x07, 0xab, 0x1b, 0x81, 0x6f, 0xc3, 0x90, 0xcb, 0x40, 0xf9, 0x34, 0x26, 0x35, 0x90, 0xde,
	0xa5, 0xe5, 0x52, 0xb9, 0x64, 0x10, 0x19, 0x62, 0x17, 0x46, 0x52, 0xc9, 0x3b, 0xba, 0x64, 0xca,
	0x26, 0x8b, 0x74, 0xd8, 0x15, 0x00, 0x57, 0x9a, 0x65, 0x47, 0x96, 0x67, 0x8b, 0x2f, 0x6d, 0x47,
	0x05, 0xa4, 0x98, 0x98, 0xbf, 0x2a, 0x93, 0x44, 0x35, 0x1d, 0x91, 0x06, 0xe1, 0x03, 0x18, 0xca,
	0x3e, 0xc7, 0x8e, 0xee, 0xe9, 0x81, 0x3d, 0xf5, 0xff, 0xed, 0x0a, 0xa9, 0x0b, 0xdc, 0xfb, 0x30,
	0x6a, 0x17, 0xc6, 0x18, 0x0c, 0x51, 0x9d, 0x1c, 0x3b, 0xc8, 0xd3, 0x03, 0x8b, 0xa8, 0xf8, 0x48,
	0x07, 0x14, 0xba, 0x3e, 0x98, 0xf5, 0x39, 0xe4, 0xf1, 0x73, 0x7a, 0x99, 0x64, 0x34, 0x6c, 0x84,
	0xb5, 0x50, 0x12, 0x97, 0x7e, 0x0e, 0x3b, 0xb3, 0x4c, 0xcc, 0x0b, 0x9a, 0x72, 0xba, 0x10, 0x71,
	0x96, 0x1e, 0x25, 0xd9, 0xe2, 0x02, 0x3f, 0x87, 0xb1, 0xb8, 0xca, 0x71, 0x35, 0xc0, 0x9e, 0xee,
	0xb4, 0x2a, 0x7b, 0x7c, 0xb2, 0x42, 0xc4, 0x1e, 0xd8, 0xe7, 0x2c, 0x8a, 0xd3, 0x53, 0x56, 0xc4,
	0x8c, 0x37, 0x4e, 0xf6, 0x53, 0xfe, 0x4f, 0x04, 0xb6, 0x5c, 0xaa, 0x59, 0x42, 0x3a, 0x14, 0xaa,
	0x55, 0x1b, 0x7d, 0x0d, 0xba, 0xe1, 0x16, 0xf7, 0xc0, 0xe2, 0x71, 0x94, 0x52, 0x51, 0x16, 0xcc,
	0x19, 0x2a, 0xf2, 0x55, 0x42, 0x4e, 0x66, 0x69, 0x98, 0x15, 0x9c, 0x2d, 0x59, 0x2a, 0xd4, 0x6b,
	0x1b, 0x93, 0x7e, 0x0a, 0x3f, 0x86, 0xed, 0x1e, 0xfc, 0xc4, 0x0a, 0xf5, 0xb2, 0xfe, 0x23, 0xd7,
	0xb2, 0xfe, 0x77, 0xd4, 0x7e, 0x4f, 0x67, 0xf3, 0x4a, 0x7e, 0x23, 0xa2, 0x6a, 0x1d, 0x70, 0x57,
	0xef, 0x74, 0x36, 0xaf, 0x26, 0xf3, 0x8a, 0xbf, 0x4c, 0x45, 0x71, 0x49, 0x24, 0xcd, 0x3d, 0x95,
	0xd7, 0xa9, 0x13, 0x72, 0x83, 0x0b, 0x76, 0xa9, 0xd6, 0xb2, 0x88, 0x0c, 0xf1, 0x1e, 0x0c, 0xbf,
	0xd1, 0xa4, 0x64, 0x6a, 0x2b, 0x7b, 0x7a, 0xb7, 0xed, 0x76, 0xc3, 0x09, 0x48, 0xcd, 0x3c, 0xd4,
	0x0e, 0x90, 0xff, 0x03, 0xc1, 0x76, 0x37, 0xb0, 0x76, 0x6d, 0xaf, 0xaf, 0xea, 0xc1, 0x9a, 0x2a,
	0x45, 0xba, 0x26, 0xed, 0xcd, 0x5f, 0xa5, 0x3d, 0x59, 0x95, 0xd6, 0x9d, 0xba, 0x77, 0xaa, 0x9e,
	0xa4, 0xe9, 0x21, 0x98, 0xf5, 0x30, 0xbc, 0x0b, 0xda, 0x49, 0x8a, 0x6f, 0xad, 0x3d, 0x60, 0x77,
	0x3d, 0xe5, 0x0f, 0x02, 0xb4, 0x8b, 0xce, 0xeb, 0x7f, 0xb1, 0xfd, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x79, 0x26, 0x8a, 0x4b, 0xdc, 0x04, 0x00, 0x00,
}
